### ISSUE TITLE
README lacking

### ISSUE THREAD

**Issue by jvoigtlaender** [rtfeldman/elm-bin#2]
Please take over the README from https://github.com/kevva/elm-bin/blob/master/readme.md.

Specifically, it's harmful (at the moment, for Elm 0.15.1) that you elided the comment about `ELM_HOME`.

See [this](https://groups.google.com/d/msg/elm-discuss/jY9BNp5HEY4/BuKOlS59AwAJ) on the mailing list.

**Comment by rtfeldman** [comment]
Moving to https://github.com/elm-lang/elm-platform/issues/95
